name: Simple CI Pipeline

on:
  push:                # 当推送代码时触发
    branches: [ "main" ]
  pull_request:        # 或者PR时触发
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run tests
        run: |
          pytest -v
